import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Navbar'

const roboto = Roboto({weight:"400",subsets:["latin"]})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className='container h-screen w-screen overflow-hidden flex flex-row'>
          {/* <NavBar></NavBar> */}
          {children}
        </div>
      </body>
    </html>
  )
}
